# Generated by Django 5.1.1 on 2025-04-09 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcName', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=2, unique=True)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('housePrice', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='CostLiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familySize', models.IntegerField(choices=[(1, '1'), (4, '4')])),
                ('accom', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('util', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('food', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('transport', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('other', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicstats.postcodeinfo')),
            ],
            options={
                'unique_together': {('familySize', 'postcode')},
            },
        ),
    ]
